# Generated by Django 6.0.4 on 2026-04-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_subscription_options_alter_tariff_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text="O'zbek so'mida. Masalan: 199000", max_digits=12, verbose_name='Narxi (UZS)'),
        ),
    ]
