# Generated by Django 6.0.4 on 2026-04-25 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_price_to_uzs'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='month_reset_date',
            field=models.DateField(blank=True, help_text='Bu sana kelganda sites_created_this_month 0 ga resetlanadi.', null=True, verbose_name='Oylik reset sanasi'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='sites_created_this_month',
            field=models.PositiveIntegerField(default=0, verbose_name='Bu oy yaratilgan saytlar'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='max_sites_per_month',
            field=models.IntegerField(default=3, help_text='Foydalanuvchi bir oyda yarata oladigan yangi saytlar soni. 0 = cheksiz.', verbose_name='Oylik yangi sayt limiti'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='projects_created',
            field=models.IntegerField(default=0, verbose_name='Jami yaratilgan loyihalar'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='projects_limit',
            field=models.IntegerField(default=1, verbose_name='Faol saytlar soni'),
        ),
    ]
