# Generated by Django 6.0.4 on 2026-04-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_subscription_month_reset_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='max_active_sites',
            field=models.IntegerField(default=0, help_text='0 = projects_limit bilan bir xil. Aks holda alohida cheklov.', verbose_name='Bir vaqtdagi maks. faol saytlar'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='storage_limit_mb',
            field=models.IntegerField(default=100, help_text="Hosting'da har sayt uchun maksimal disk hajmi (MB).", verbose_name='Saqlash hajmi (MB)'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='traffic_limit_gb',
            field=models.IntegerField(default=1, help_text='Oyiga maksimal trafik (GB). 0 = cheksiz.', verbose_name='Oylik trafik (GB)'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='projects_limit',
            field=models.IntegerField(default=1, help_text="Bir vaqtning o'zida ushlab turish mumkin bo'lgan faol saytlar.", verbose_name='Faol saytlar soni'),
        ),
    ]
