# Generated by Django 6.0.4 on 2026-04-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteproject',
            name='generation_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
