# Generated by Django 6.0.4 on 2026-04-20 10:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_projects', '0002_websiteproject_generation_started_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('schema_data', models.JSONField()),
                ('intent', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='website_projects.websiteproject')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('project', 'version_number')},
            },
        ),
    ]
