# Generated by Django 6.0.4 on 2026-04-25 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_projects', '0007_websiteproject_publish_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteproject',
            name='hosted_on_platform',
            field=models.BooleanField(default=True, help_text='Faqat nanostup.uz/s/<slug> orqali ishlaydi.', verbose_name='Platformada hosting'),
        ),
        migrations.AddField(
            model_name='websiteproject',
            name='is_active',
            field=models.BooleanField(default=True, help_text="False bo'lsa publik URL 402 qaytaradi (obuna tugagan).", verbose_name='Sayt faolmi'),
        ),
    ]
