# Generated by Django 6.0.4 on 2026-04-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_projects', '0008_websiteproject_hosted_on_platform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteproject',
            name='hosted_on_platform',
            field=models.BooleanField(default=True, help_text='Saytlar faqat NanoStUp serverlarida ishlaydi (external hosting taqiqlangan).', verbose_name="NanoStUp'da hosting"),
        ),
        migrations.AlterField(
            model_name='websiteproject',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Sayt publik URL orqali ko'rinadimi? Obuna tugaganda yoki admin tomonidan bloklanganda False qilinadi.", verbose_name='Faol'),
        ),
    ]
