# Generated by Django 6.0.4 on 2026-04-29 22:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_projects', '0009_alter_websiteproject_hosted_on_platform_and_more'),
        ('subscriptions', '0007_backfill_admin_manual_payments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteproject',
            name='custom_domain',
            field=models.CharField(blank=True, db_index=True, help_text="Misol: mysite.com. Pro+ tarif uchun. DNS A-record nanostup-api'ga yo'naltirilishi kerak.", max_length=253, verbose_name='Custom domen'),
        ),
        migrations.AddField(
            model_name='websiteproject',
            name='custom_domain_verified',
            field=models.BooleanField(default=False, help_text="DNS to'g'ri sozlanganmi? Avto-tekshiriladi.", verbose_name='Domen tasdiqlangan'),
        ),
        migrations.AddField(
            model_name='websiteproject',
            name='hosting_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text="Sayt hosting muddati. NULL bo'lsa cheksiz (TRIAL/ARCHIVED).", null=True, verbose_name='Hosting tugash sanasi'),
        ),
        migrations.AddField(
            model_name='websiteproject',
            name='hosting_status',
            field=models.CharField(choices=[('ACTIVE', 'Faol'), ('TRIAL', 'Sinov'), ('EXPIRED', 'Muddati tugagan'), ('SUSPENDED', "To'xtatilgan"), ('ARCHIVED', 'Arxivlangan')], db_index=True, default='TRIAL', help_text="Sayt hosting holati. Subscription tugaganda EXPIRED bo'ladi (soft-lock).", max_length=20, verbose_name='Hosting holati'),
        ),
        migrations.AddField(
            model_name='websiteproject',
            name='suspension_reason',
            field=models.CharField(blank=True, help_text="EXPIRED yoki SUSPENDED holatda foydalanuvchiga ko'rsatiladigan xabar.", max_length=255, verbose_name="To'xtatish sababi"),
        ),
        migrations.AlterField(
            model_name='websiteproject',
            name='is_active',
            field=models.BooleanField(default=True, help_text='ESKI: hosting_status orqali ishlash kerak. False = SUSPENDED ekvivalent.', verbose_name='Faol (deprecated)'),
        ),
        migrations.AddIndex(
            model_name='websiteproject',
            index=models.Index(fields=['hosting_status', '-updated_at'], name='website_pro_hosting_93a858_idx'),
        ),
        migrations.AddIndex(
            model_name='websiteproject',
            index=models.Index(fields=['user', 'hosting_status'], name='website_pro_user_id_b0f3b6_idx'),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: _backfill_hosting_status(apps, schema_editor),
            reverse_code=migrations.RunPython.noop,
        ),
    ]


def _backfill_hosting_status(apps, schema_editor):
    """
    Eski saytlarni hosting_status bilan to'ldirish:
      - is_published+is_active=True va user obunasi faol → ACTIVE + end_date
      - is_published+is_active=True, obuna yo'q → TRIAL (cheksiz, eski mantiq buzilmasin)
      - is_active=False                       → SUSPENDED
      - boshqa (ishlatilmagan)                → TRIAL
    """
    WebsiteProject = apps.get_model('website_projects', 'WebsiteProject')
    Subscription = apps.get_model('subscriptions', 'Subscription')

    # Foydalanuvchi → faol obuna end_date kesh
    user_active_end = {}
    for sub in Subscription.objects.filter(status='ACTIVE'):
        # Eng kech tugaydigan obunani saqlaymiz
        prev = user_active_end.get(sub.user_id)
        if not prev or (sub.end_date and prev < sub.end_date):
            user_active_end[sub.user_id] = sub.end_date

    for project in WebsiteProject.objects.all():
        if not project.is_active:
            project.hosting_status = 'SUSPENDED'
            project.suspension_reason = 'Avval is_active=False bo\'lgan'
        elif project.is_published:
            end = user_active_end.get(project.user_id)
            if end:
                project.hosting_status = 'ACTIVE'
                project.hosting_expires_at = end
            else:
                project.hosting_status = 'TRIAL'
        else:
            project.hosting_status = 'TRIAL'
        project.save(update_fields=['hosting_status', 'hosting_expires_at', 'suspension_reason'])
