# Generated by Django 6.0.4 on 2026-04-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_tokens_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tokens_balance',
            field=models.PositiveIntegerField(default=5000, help_text='Foydalanuvchining joriy token balansi', verbose_name='tokens balance'),
        ),
    ]
