# Generated by Django 6.0.4 on 2026-04-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_adjust_default_bonus_to_500_nano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tokens_balance',
            field=models.PositiveIntegerField(default=100000, help_text='Foydalanuvchining joriy token balansi', verbose_name='tokens balance'),
        ),
    ]
