# Generated by Django 6.0.4 on 2026-04-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_update_default_tokens_to_100000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tokens_balance',
            field=models.PositiveIntegerField(default=30000, help_text='Foydalanuvchining joriy token balansi', verbose_name='tokens balance'),
        ),
    ]
