# Generated by Django 6.0.4 on 2026-04-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_registration_bonus_3000_nano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tokens_balance',
            field=models.PositiveIntegerField(default=10000, help_text='Foydalanuvchining joriy token balansi', verbose_name='tokens balance'),
        ),
    ]
