# Generated by Django 6.0.4 on 2026-04-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_tokens_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nano_coins_last_used_at',
            field=models.DateTimeField(blank=True, default=None, help_text="30 kun ishlatmasa nano koin balansi 0'ga tushadi (use-it-or-lose-it)", null=True, verbose_name='nano koin oxirgi ishlatilgan'),
        ),
    ]
