import io
import zipfile
import json
from django.conf import settings
from apps.website_projects.models import WebsiteProject

class ExportService:
    @staticmethod
    def generate_static_zip(project: WebsiteProject) -> io.BytesIO:
        """
        Generates a ZIP file containing static HTML/CSS/JS for the project.
        """
        buffer = io.BytesIO()
        with zipfile.ZipFile(buffer, 'w', zipfile.ZIP_DEFLATED) as zip_file:
            # 1. Add static index.html (Simplified version)
            index_html = f"""
            <!DOCTYPE html>
            <html lang="{project.language}">
            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>{project.title}</title>
                <script src="https://cdn.tailwindcss.com"></script>
            </head>
            <body class="bg-gray-50">
                <div id="root">
                    <h1 class="text-4xl font-bold text-center mt-20">{project.title}</h1>
                    <p class="text-center text-gray-500 mt-4">Static site generated by AI Builder.</p>
                </div>
            </body>
            </html>
            """
            zip_file.writestr('index.html', index_html)
            
            # 2. Add schema.json for reference
            if project.schema_data:
                zip_file.writestr('schema.json', json.dumps(project.schema_data, indent=2))
        
        buffer.seek(0)
        return buffer
